spring:
  application:
    name: greeter-cloud-app
  cloud:
    config:
      # label: master
      uri: http://localhost:8888/
eureka:
  instance:
      hostname: localhost
      port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/