info:
    component: greeter cloud app
eureka:
    instance:
        hostname: localhost
        port: 8081
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

logging:
    level:
        root: WARN
        org.springframework.web: INFO
        org.springframework.security: INFO