server:
  port: 8766
spring:
  application:
    name: greeter-feign
eureka:
  instance:
      hostname: localhost
      port: 8081
      prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/